name: app_intents_annotations
description: Annotations for defining iOS App Intents in Flutter. Use with app_intents and app_intents_codegen.
version: 0.1.0
repository: https://github.com/touyou/flutter_intents

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
