name: app_intents_codegen
description: Code generator for Flutter AppIntents. Produces Swift and Dart code from @IntentSpec and @EntitySpec annotations.
version: 0.1.0
repository: https://github.com/touyou/flutter_intents

environment:
  sdk: ^3.10.0

dependencies:
  analyzer: ^7.0.0
  args: ^2.5.0
  build: ^2.4.0
  source_gen: ^2.0.0
  code_builder: ^4.10.0
  dart_style: ^3.0.0
  glob: ^2.1.0
  path: ^1.9.0
  app_intents_annotations: ^0.1.0

executables:
  generate_swift: generate_swift

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_test: ^2.2.0
